<?php
$viewModel = $block->getViewModel();
?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getFormAction(); ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                       
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="">
                                <input name="name" id="name" value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>" class="input-text" type="text">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>" class="input-text"
                                       type="text">
                            </div>
                        </div>
                        <div class="field telephone required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                        <input name="telephone" id="telephone" value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>" class="input-text" type="text">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
     
    </div>
</div> 
<script type="text/x-magento-init">
{
"*": {
"Magento_Customer/js/block-submit-on-send": {
"formId": "jobapply-form"
}
}
}
</script>